#!/bin/bash

echo "🎯 Adding checkout.session.completed Event"
echo "=========================================="
echo ""
echo "The missing event has been identified!"
echo ""
echo "Your webhook URL: https://stripewebhook-r7yfhehdra-uc.a.run.app"
echo ""
echo "📋 Quick Fix Steps:"
echo ""
echo "1️⃣  Open Stripe Dashboard:"
echo "   https://dashboard.stripe.com/test/webhooks"
echo "   (or https://dashboard.stripe.com/webhooks for live mode)"
echo ""
echo "2️⃣  Click on your webhook endpoint"
echo ""
echo "3️⃣  Scroll down to 'Events to send' section"
echo ""
echo "4️⃣  Click '+ Select events' or 'Add events'"
echo ""
echo "5️⃣  Search for and select:"
echo "   ✅ checkout.session.completed  <-- THIS IS THE ONE YOU NEED!"
echo ""
echo "6️⃣  Click 'Add events' to save"
echo ""
echo "=========================================="
echo ""
read -p "Press Enter after you've added the event in Stripe Dashboard..."
echo ""
echo "7️⃣  Test the webhook:"
echo ""
echo "Option A - Test in Stripe:"
echo "  1. Stay on webhook page"
echo "  2. Click 'Send test webhook'"
echo "  3. Select 'checkout.session.completed'"
echo "  4. Click 'Send test webhook'"
echo "  5. Should see: 200 OK ✅"
echo ""
echo "Option B - Real test payment:"
echo "  1. Run your app"
echo "  2. Go to Premium Purchase"
echo "  3. Use card: 4242 4242 4242 4242"
echo "  4. Complete payment"
echo "  5. Check webhook logs:"
echo ""

read -p "Want to view webhook logs now? (y/n): " view_logs

if [ "$view_logs" = "y" ]; then
    echo ""
    echo "📊 Recent webhook logs:"
    echo "======================"
    firebase functions:log | grep -i "stripe" | tail -20
fi

echo ""
echo "=========================================="
echo "✅ Done!"
echo ""
echo "Your webhook should now receive payment completion events."
echo "Try making a test payment - premium should activate automatically!"
echo ""
