#!/bin/bash

# Check Premium Status Script
# Helps verify if premium is activated in Firestore

echo "🔍 Premium Status Checker"
echo "========================"
echo ""

echo "This script will help you check if your premium status is correctly set in Firebase."
echo ""

read -p "Enter your email address (used for the app): " user_email

if [ -z "$user_email" ]; then
    echo "❌ No email provided"
    exit 1
fi

echo ""
echo "📋 Manual Check Steps:"
echo "======================"
echo ""
echo "1. Open Firebase Console:"
echo "   https://console.firebase.google.com/project/brownclaw/firestore"
echo ""
echo "2. Navigate to 'users' collection"
echo ""
echo "3. Find your user:"
echo "   - Look for email: $user_email"
echo "   - Or search by clicking 'Start collection' > 'Add filter'"
echo "   - Filter: email == $user_email"
echo ""
echo "4. Check your user document has these fields:"
echo "   ✅ isPremium: true (boolean)"
echo "   ✅ stripeCustomerId: cus_XXXXX (string)"
echo "   ✅ subscriptionId: sub_XXXXX (string)"  
echo "   ✅ subscriptionStatus: active (string)"
echo ""
echo "5. If 'isPremium' is false or missing:"
echo "   - Click 'Edit document'"
echo "   - Add field: isPremium (boolean) = true"
echo "   - Add field: subscriptionStatus (string) = active"
echo "   - Click 'Update'"
echo ""
echo "========================"
echo ""
echo "📊 Alternative: Check Stripe Dashboard"
echo "======================================="
echo ""
echo "1. Check if payment succeeded:"
echo "   https://dashboard.stripe.com/payments"
echo "   - Look for payment from: $user_email"
echo "   - Status should be: Succeeded"
echo ""
echo "2. Check subscription:"
echo "   https://dashboard.stripe.com/subscriptions"
echo "   - Find subscription for: $user_email"
echo "   - Status should be: Active"
echo ""
echo "3. Check webhook events:"
echo "   https://dashboard.stripe.com/webhooks"
echo "   - Click on your webhook"
echo "   - Look at recent deliveries"
echo "   - Should see: checkout.session.completed (200 OK)"
echo ""
echo "========================"
echo ""
echo "🔧 Quick Fixes:"
echo "==============="
echo ""
echo "If premium is not active after successful payment:"
echo ""
echo "Option 1: Manually activate (recommended)"
echo "   Run: ./manual_activate_premium.sh $user_email"
echo ""
echo "Option 2: Fix webhook and retry payment"
echo "   Run: ./fix_stripe_webhook.sh"
echo ""
echo "Option 3: Check function logs for errors"
echo "   Run: firebase functions:log --only stripeWebhook"
echo ""
