name: brownclaw
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.3
  google_sign_in: ^6.2.1
  http: ^1.1.0
  fl_chart: ^0.69.0
  provider: ^6.1.2
  flutter_stripe: ^11.1.0
  cloud_functions: ^5.1.3
  shared_preferences: ^2.2.2  # For local caching and data persistence

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/brownclaw.png
    - assets/brownclaw_optimized.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/brownclaw.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/brownclaw.png"
  windows:
    generate: true
    image_path: "assets/brownclaw.png"
  macos:
    generate: true
    image_path: "assets/brownclaw.png"
